name: Ingredient price scanner 💰

on:
  schedule:
    - cron:  '0 0 * * *'  # This will run the action every day at midnight
  workflow_dispatch: # Can also be triggered manually if needed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run update script
      run: pnpm exec node ./scripts/price-scanner.js
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        KASSALAPP_API_KEY: ${{ secrets.KASSALAPP_API_KEY }}
